name: dev-CI

on:
  push:
    branches:
      - "develop"

env:
  ECR_REPOSITORY: dev_sia_cicd
  PROFILE: local
  TAG: latest

jobs:
  tagging-job:
    runs-on: ubuntu-latest
    steps:
      - name: get current datetime
        id: version_up
        run: |
          echo "tag_version=dev-$(date -d 'now + 9 hours' '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    outputs:
      TAG_VERSION: ${{ steps.version_up.outputs.tag_version }}

  docker-image-build:
    needs: tagging-job
    runs-on: ubuntu-latest
    steps:
      - name: logging
        id: test
        run: echo ${{ needs.tagging-job.outputs.TAG_VERSION }}
      # checkout후 자바 17 버전으로 설정을 합니다..
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'


      ## gradlew 의 권한을 줍니다..
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

     ## 빌드
      - name: Build with Gradle
        run: ./gradlew build -PappVersion=$TAG

      ## AWS에 로그인
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      ## ECR에 로그인합니다
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ## ECR DOCKER IMAGE PUSH
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build --build-arg VERSION=$TAG --build-arg PROFILE=$PROFILE -t $ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }} .
          docker tag $ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }} 992382734108.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }}
          docker push 992382734108.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }}