name: dev-CICD

on:
  push:
    branches:
      - "develop"

env:
  ECR_REPOSITORY: dev-sia-cicd-repository
  ECS_SERVICE: dev-sia-cicd-service
  ECS_CLUSTER: dev-sia-cicd-cluster
  ECS_CONTAINER_NAME: dev-sia-cicid-container
  TASK_DEFINITION_NAME: dev-sia-cicd-task
  PROFILE: dev
  TAG: latest

jobs:
  ## Tagging 정책 설정
  tagging-job:
    runs-on: ubuntu-latest
    steps:
      - name: get current datetime
        id: version_up
        run: |
          echo "tag_version=dev-$(date -d 'now + 9 hours' '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    outputs:
      TAG_VERSION: ${{ steps.version_up.outputs.tag_version }}

  docker-image-build:
    needs: tagging-job
    runs-on: ubuntu-latest
    steps:
      - name: logging
        id: test
        run: echo ${{ needs.tagging-job.outputs.TAG_VERSION }}
      # checkout후 자바 17 버전으로 설정을 합니다..
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      ## gradlew 의 권한을 줍니다..
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ## 빌드
      - name: Build with Gradle
        run: ./gradlew build -PappVersion=$TAG

      ## AWS에 로그인
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      ## ECR에 로그인합니다
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ## ECR DOCKER IMAGE PUSH
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build --build-arg VERSION=$TAG --build-arg PROFILE=$PROFILE -t $ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }} .
          docker tag $ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }} 992382734108.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }}
          docker push 992382734108.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPOSITORY:${{ needs.tagging-job.outputs.TAG_VERSION }}

  push-ecs:
    needs:
      - tagging-job
      - docker-image-build
    runs-on: ubuntu-latest
    steps:
      ## AWS에 로그인
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      ## Task Definition Template 다운로드
      - name: Download Task Definition Template
        id: retrieve-task-def
        run: |
          aws ecs describe-task-definition --task-definition $TASK_DEFINITION_NAME --query taskDefinition > task-definition.json
          cat task-definition.json
          echo "::set-output name=task-def-file::task-definition.json"

      ## Task Definition image 설정
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.retrieve-task-def.outputs.task-def-file }}
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: 992382734108.dkr.ecr.ap-northeast-2.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ needs.tagging-job.outputs.TAG_VERSION }}

      ## Task 실행
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
